name: PR Reviewer Bot

on:
  pull_request:
    types: [opened, synchronize]

# Prevent multiple runs for same PR
concurrency:
  group: pr-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better diff analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'  # Built-in caching

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.GROQ_API_KEY }}" ]; then
            echo "❌ Error: GROQ_API_KEY secret is not configured"
            echo "Please add it in repository Settings > Secrets and variables > Actions"
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests==2.31.0 groq==0.4.2

      - name: Run PR reviewer
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python review_bot.py

      - name: Report completion
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ PR review completed successfully"
          else
            echo "⚠️ PR review completed with issues (check logs above)"
          fi